SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [t_Social_ConversationField](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[IfSystem] [bit] NOT NULL,
	[DataType] [smallint] NOT NULL,
	[Name] [nvarchar](max) NULL,
	[SiteId] [int] NOT NULL,
 CONSTRAINT [PK_t_Social_ConversationField] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO